version: '3.5'

services:
  integor_telegram_bots_events_db:
    image: postgres:14.5
    container_name: integor_telegram_bots_events_db
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=integor_telegram_bots_events
    networks:
      - integor_telegram_bots_events_network

  telegram_bots_events_db_admin:
    image: dpage/pgadmin4:6.20
    container_name: integor_telegram_bots_events_db_admin
    ports:
      - "8081:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=logunov.stepan2001@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234567890
      - PGADMIN_LISTEN_PORT=80
    networks:
      - integor_telegram_bots_events_network
  
networks:
  integor_telegram_bots_events_network:
    driver: bridge
    