// <auto-generated />
using System;
using IntegorTelegramBotListeningServices.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IntegorTelegramBotListeningServices.Migrations
{
    [DbContext(typeof(IntegorTelegramBotListeningDataContext))]
    [Migration("20230426154019_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IntegorTelegramBotListeningServices.EntityFramework.Model.EfTelegramBot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Bots");
                });

            modelBuilder.Entity("IntegorTelegramBotListeningServices.EntityFramework.Model.EfTelegramChat", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool?>("IsForum")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("IntegorTelegramBotListeningServices.EntityFramework.Model.EfTelegramMessage", b =>
                {
                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FromId")
                        .HasColumnType("bigint");

                    b.Property<int>("RelatedBotId")
                        .HasColumnType("integer");

                    b.Property<long?>("ReplyToMessageChatId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReplyToMessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("MessageId", "ChatId");

                    b.HasIndex("ChatId");

                    b.HasIndex("FromId");

                    b.HasIndex("RelatedBotId");

                    b.HasIndex("ReplyToMessageId", "ReplyToMessageChatId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("IntegorTelegramBotListeningServices.EntityFramework.Model.EfTelegramUser", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AggregatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IntegorTelegramBotListeningServices.EntityFramework.Model.EfTelegramMessage", b =>
                {
                    b.HasOne("IntegorTelegramBotListeningServices.EntityFramework.Model.EfTelegramChat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntegorTelegramBotListeningServices.EntityFramework.Model.EfTelegramUser", "From")
                        .WithMany("Messages")
                        .HasForeignKey("FromId");

                    b.HasOne("IntegorTelegramBotListeningServices.EntityFramework.Model.EfTelegramBot", "RelatedBot")
                        .WithMany("RelatedMessages")
                        .HasForeignKey("RelatedBotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntegorTelegramBotListeningServices.EntityFramework.Model.EfTelegramMessage", "ReplyToMessage")
                        .WithMany()
                        .HasForeignKey("ReplyToMessageId", "ReplyToMessageChatId");

                    b.Navigation("Chat");

                    b.Navigation("From");

                    b.Navigation("RelatedBot");

                    b.Navigation("ReplyToMessage");
                });

            modelBuilder.Entity("IntegorTelegramBotListeningServices.EntityFramework.Model.EfTelegramBot", b =>
                {
                    b.Navigation("RelatedMessages");
                });

            modelBuilder.Entity("IntegorTelegramBotListeningServices.EntityFramework.Model.EfTelegramChat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("IntegorTelegramBotListeningServices.EntityFramework.Model.EfTelegramUser", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
